USE [Less.WellDB]
GO

CREATE TABLE [dbo].[Wells](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DbGeography] [geography] NULL,
	[Longitude] [float] NOT NULL,
	[Latitude] [float] NOT NULL,
	[Info] [nvarchar](max) NULL
 CONSTRAINT [PK_dbo.Wells] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO